# Generated by Django 3.2.9 on 2021-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('tags', models.IntegerField()),
                ('date', models.DateField(verbose_name='post date')),
            ],
        ),
    ]
