# Generated by Django 3.2.9 on 2021-11-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20211123_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('j', 'junto'), ('c', 'CSS')], default='j', max_length=1),
        ),
    ]
