# Generated by Django 3.2.9 on 2021-11-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('J', 'Junto'), ('C', 'CSS')], default='J', max_length=1),
        ),
    ]
